dist: xenial

git:
  depth: false

language: python

python:
  - 3.8

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r requirements-test.txt

env:
  - MPLBACKEND=Agg

cache: pip

script:
  - python -m pip install --editable .
  - python -m pytest --cov=mibi_bin_tools --pycodestyle tests/* mibi_bin_tools

after_success:
  - coveralls